/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "???????, sbfspot ? ???? ?????? ?????? ???????? ? ????? ???????": {"en": "adapter, sbfspot and database should run on the same system", "de": "Der Adapter, sbfspot und die Datenbank sollte auf dem gleichen System laufen", "ru": "adapter, sbfspot and database should run on the same system", "pt": "adaptador, sbfspot e banco de dados devem ser executados no mesmo sistema", "nl": "adapter, sbfspot en database moeten op hetzelfde systeem worden uitgevoerd", "fr": "L'adaptateur, sbfspot et la base de donn�es doivent fonctionner sur le m�me syst�me", "it": "adattatore, sbfspot e database dovrebbero essere eseguiti sullo stesso sistema", "es": "adaptador, sbfspot y base de datos deben ejecutarse en el mismo sistema", "pl": "adapter, sbfspot i baza danych powinny dzia?a? w tym samym systemie"},
    "????????? ??? mySQL: ??????????? localhost ??? IP-?????": {"en": "hint for mySQL: use localhost as IP",             "de": "Hinweis für mySQL: localhost kann als IP verwendet werden", "ru": "hint for mySQL: use localhost as IP",             "pt": "sugest�o para mySQL: use localhost como IP",     "nl": "hint voor mySQL: gebruik localhost als IP",      "fr": "indice pour mySQL: utilisez localhost comme IP", "it": "suggerimento per mySQL: usa localhost come IP",  "es": "sugerencia para mySQL: use localhost como IP",   "pl": "wskaz�wka dla mySQL: u?yj localhost jako IP"},
    "????????? ??? sqlite: ??????? ?????? ????, ???. ??? ????? ???? ??????, ????????. /home/pi/sbfspot/smadata/SBFspot.db": {"en": "hint for sqlite: enter the complete path incl. database file name e.g. /home/pi/sbfspot/smadata/SBFspot.db", "de": "Hinweis für sqlite: Der Pfad muss komplett inkl. Datenbankfilename angegeben werden. z.Bsp. /home/pi/sbfspot/smadata/SBFspot.db", "ru": "hint for sqlite: enter the complete path incl. database file name e.g. /home/pi/sbfspot/smadata/SBFspot.db", "pt": "sugest�o para sqlite: insira o caminho completo incl. nome do arquivo do banco de dados, e. /home/pi/sbfspot/smadata/SBFspot.db", "nl": "hint voor sqlite: vul het volledige pad in incl. databasebestandsnaam, b.v. /home/pi/sbfspot/smadata/SBFspot.db", "fr": "indice pour sqlite: entrez le chemin complet incl. nom de fichier de base de donn�es, par ex. /home/pi/sbfspot/smadata/SBFspot.db", "it": "suggerimento per sqlite: inserire il percorso completo incl. nome del file di database, ad es. /home/pi/sbfspot/smadata/SBFspot.db", "es": "pista para sqlite: ingrese la ruta completa incl. nombre de archivo de base de datos, p. /home/pi/sbfspot/smadata/SBFspot.db", "pl": "wskaz�wka dla sqlite: wprowad? pe?n? ?cie?k? w??cznie nazwa pliku bazy danych, np. /home/pi/sbfspot/smadata/SBFspot.db"},
    "???? ????????? PV-???????": {                  "en": "install date PV-System",                          "de": "Installationsdatum PV-Anlage",                    "ru": "install date PV-System",                          "pt": "data de instala��o PV-System",                   "nl": "installeer datum PV-systeem",                    "fr": "date d'installation PV-System",                  "it": "installare data PV-System",                      "es": "fecha de instalaci�n PV-System",                 "pl": "data instalacji PV-System"},
    "???????????? ??? ??????? ??????? ? ????????": {"en": "used for calculation of history in vis widget",   "de": "wird für Berechnung der Statistik im vis widget verwendet", "ru": "used for calculation of history in vis widget",   "pt": "usado para calcular o hist�rico no vis widget",  "nl": "gebruikt voor de berekening van de geschiedenis in vis widget", "fr": "utilis� pour le calcul de l'histoire dans vis widget", "it": "utilizzato per il calcolo della cronologia nel widget vis", "es": "utilizado para el c�lculo de la historia en el widget vis", "pl": "s?u?y do obliczania historii w widgecie vis"},
    "?? ???????????????? ???????? ??????????????? ? ????? ????????????? ??????????": {"en": "on save adapter restarts with new config immediately", "de": "Beim Speichern von Einstellungen wird der Adapter sofort neu gestartet.", "ru": "on save adapter restarts with new config immediately", "pt": "no adaptador de salvar reinicia com nova configura��o imediatamente", "nl": "on save-adapter wordt onmiddellijk opnieuw opgestart met nieuwe config", "fr": "sur l'adaptateur de sauvegarde red�marre avec la nouvelle config imm�diatement", "it": "su save adapter si riavvia immediatamente con la nuova configurazione", "es": "en el adaptador de guardar se reinicia con nueva configuraci�n de inmediato", "pl": "na karcie save natychmiast uruchamia si? z now? konfiguracj?"},
    "???? ? ????? ???? ?????? sqlite": {            "en": "path to sqlite database file",                    "de": "Pfad zur sqlite-Datenbank",                       "ru": "path to sqlite database file",                    "pt": "caminho para o arquivo de banco de dados sqlite", "nl": "pad naar sqlite databasebestand",                "fr": "chemin vers le fichier de base de donn�es sqlite", "it": "percorso per il file di database sqlite",        "es": "ruta al archivo de base de datos sqlite",        "pl": "?cie?ka do pliku bazy danych sqlite"},
    "IP-????? mySQL": {                             "en": "mySQL database IP",                               "de": "mySQL Datenbank-IP",                              "ru": "mySQL database IP",                               "pt": "banco de dados MySQL",                           "nl": "mySQL database IP",                              "fr": "base de donn�es mySQL IP",                       "it": "IP del database mySQL",                          "es": "base de datos mySQL IP",                         "pl": "IP bazy danych MySQL"},
    "??? ???? ?????? mySQL": {                      "en": "mySQL database name",                             "de": "mySQL Datenbank-Name",                            "ru": "mySQL database name",                             "pt": "Nome do banco de dados mySQL",                   "nl": "mySQL-databasenaam",                             "fr": "Nom de la base de donn�es mySQL",                "it": "nome del database mySQL",                        "es": "nombre de la base de datos mySQL",               "pl": "nazwa bazy danych mySQL"},
    "?????? ???? ?????? mySQL": {                   "en": "mySQL database password",                         "de": "mySQL Datenbank_Passwort",                        "ru": "mySQL database password",                         "pt": "senha do banco de dados mySQL",                  "nl": "mySQL database wachtwoord",                      "fr": "Mot de passe de base de donn�es mySQL",          "it": "password del database mySQL",                    "es": "contrase�a de la base de datos mySQL",           "pl": "Has?o bazy danych MySQL"},
    "???????????? ???? ?????? mySQL": {             "en": "mySQL database user",                             "de": "mySQL Datenbank-Benutzer",                        "ru": "mySQL database user",                             "pt": "usu�rio do banco de dados mySQL",                "nl": "mySQL-databasegebruiker",                        "fr": "utilisateur de base de donn�es mySQL",           "it": "utente del database mySQL",                      "es": "usuario de la base de datos mySQL",              "pl": "u?ytkownik bazy danych mySQL"},
    "????????? ???????? sbfspot": {                 "en": "sbfspot adapter settings",                        "de": "sbfspot Adapter Einstellungen",                   "ru": "sbfspot adapter settings",                        "pt": "Configura��es do adaptador sbfspot",             "nl": "sbfspot-adapterinstellingen",                    "fr": "Param�tres de l'adaptateur sbfspot",             "it": "impostazioni dell'adattatore sbfspot",           "es": "Configuraci�n del adaptador sbfspot",            "pl": "Ustawienia adaptera sbfspot"},
    "??? ???? ??????": {                             "en": "type of database",                                "de": "Type der Datenbank",                              "ru": "type of database",                                "pt": "tipo de banco de dados",                          "nl": "type database",                                   "fr": "type de base de donn�es",                         "it": "tipo di database",                                "es": "tipo de base de datos",                           "pl": "typ bazy danych"},
};